### ISSUE TITLE
The infinite signal list bug

### ISSUE THREAD

**Issue by Suor** [ionelmc/python-redis-lock#15]
If I use only non-blocking acquires then nobody will consume signal list, but every process will push to it on release, so signal list will grow indefinitely.

And mixing blocking and non-blocking locks will end up in a total nightmare.

See #14 for related bug.

**Comment by ionelmc** [comment]
Just to make sure I understood this, this would be fixed by what's being proposed in #14 yes?

**Comment by Suor** [comment]
It should. You can create a separate test on it, though. Like make 1 non-blocking, then 2 blocking and check they don't go in parallel.

**Comment by ionelmc** [comment]
Yes, so mixing blocking with nonblocking acquires will lead to some inefficiencies at release. Because we can't know what the next acquire will be (blocking or nonblocking) we need to always push the signals.

I'm changing the release code to cleanup the signal queue - so there's at most 1 item in that list. I think this is acceptable - it will only create at most 1 wasteful wakeup.

Thanks for the report.
