### ISSUE TITLE
Storing additional metadata with the lock

### ISSUE THREAD

**Issue by ParthGandhi** [ionelmc/python-redis-lock#68]
I want to store some metadata with the lock eg. `ip-address` of box holding the lock, `time_acquired` of the lock, etc. 

I have a thin layer on top of this lib where i do some application specific stuff. I can think of 2 options to storing this metadata:
1) serialize a dict of the data into a string and use that as the lock `id` i.e. ```redis_lock.Lock(conn, redis_key, id=json.dumps({...}))```
2) the application layer stores the metadata in another redis-key that gets written when the lock is acquired and deleted when the lock is released.

Option (1) is definitely easier, but maybe too hacky? Do you see any downsides to this approach?

Another, related, question is: the docs for `id` in the constructor say:
" The ID (redis value) the lock should have. A random value is generated when left at the default. Note that if you specify this then the lock is marked as "held". Acquires won't be possible."

But i don't see the constructor doing anything special when `id` is passed in. It essentially does `self._id = <id-arg> OR <generate-new-id>`, and from then on its the same. What am i missing?

Thanks!

EDIT: a drawback of (2) is that you ~2x the number of redis calls.

**Comment by damianball** [comment]
@ParthGandhi I looked at the ID code and I agree, it doesn't appear as if setting the ID via a parameter vs allowing the constructor to auto generate has any meaningful difference. 

It seems like (1) would be a better option since it gives us what we're looking for in one call, and that call is guaranteed to succeed and be cleaned up via the standard lock loop. 

My only concern would be about redis key length and if that is somehow an issue.

**Comment by prakspcd** [comment]
what about `hash(json.dumps({...}))` as a key
